### ISSUE TITLE
Citizens incompatibility with RB 1240

### ISSUE THREAD

**Issue by hiro24** [CitizensDev/Citizens#233]
It's actually pretty funny.  If there is an NPC of a player, and that player logs in, the NPC will TP to them and begin shoving them, trying to occupy the exact coordinates as the player.  Only stops if you are in a corner, then you're "inside" your NPC.  Starts moving again when you move.  tp, warp, fly, doesn't matter... NPC keeps up perfectly.  Only way to escape it is via a multiverse.  In fact, while the NPC is following, you can't even select it via right click.  You have to /npc select [id] and /npc remove.  After that, you can't talk in chat.  You have to disconnect and reconnect.  In testing, sometimes after removing the npc it left ghost npcs.

On a side note, we joked about using this feature as a "punishment" for poorly behaving players. (Suprise!! Buttsecks!) to just follow them around and annoy the piss out of them.  >:D

EDIT:  Here's another related glitch.  If a player walks by me who has an NPC named after them, I see what the NPC is set to say.

**Comment by fullwall** [comment]
Are you using the latest dev builds? Compatibility with the latest RB should be fixed there...

**Comment by hiro24** [comment]
I just put 239 on, and at first the problem persisted.  Then I removed NPC and re-added.  The player and NPC still seem to somehow be tied together.  No console errors as of yet, but when I made the NPC I had to log out and back in before I could speak in chat... not a big deal.  BUT!

Currently I cannot log in to my server now.  Since I made an NPC of myself I'm getting an error on login I've never seen before in minecraft when I try to logon:  Illegal Stance

**Comment by johnnyzerox7** [comment]
I have the same issue with 1.1.2 and 1240. I have 5 guards around my town all named Guard, and after updating to 1240, I logged in and found them all trying to stand in the same spot. I'm only able to select (by hand) one out of the five and only the one with the highest ID. If I move any one of them to another location they all move as one. I removed them and started re-adding them and as soon as the second Guard was made the first moved to the second's position and are now inseperable.

**Comment by fullwall** [comment]
Looks like a craftbukkit update may have changed something.

**Comment by Sergeant1337** [comment]
"EDIT: Here's another related glitch. If a player walks by me who has an NPC named after them, I see what the NPC is set to say."

I have this problem to.

**Comment by fullwall** [comment]
Fixed in new dev builds.
